### PR TITLE
Workaround for Japanese Windows environment

### PR DESCRIPTION
**Pull request by mizar**
- Avoiding problems with incorrect encoding
`UnicodeDecodeError: 'cp932' codec can't decode byte 0x85 in position 2897: illegal multibyte sequence`
- Added option to output directly to file
PowerShell converts encoding and newline characters when passing stdout

### CODE REVIEW

**Comment by mizar** [comment]
example:

```bash
mkdir -p .dist
python3 expand.py -o .dist/convolution.rs convolution
python3 expand.py -o .dist/dsu.rs dsu
python3 expand.py -o .dist/fenwicktree.rs fenwicktree
python3 expand.py -o .dist/lazysegtree.rs lazysegtree
python3 expand.py -o .dist/math.rs math
python3 expand.py -o .dist/maxflow.rs maxflow
python3 expand.py -o .dist/mincostflow.rs mincostflow
python3 expand.py -o .dist/modint.rs modint
python3 expand.py -o .dist/scc.rs scc
python3 expand.py -o .dist/segtree.rs segtree
python3 expand.py -o .dist/string.rs string
python3 expand.py -o .dist/twosat.rs twosat
python3 expand.py -o .dist/all.rs --all
```

**Comment by mizar** [comment]
- Specify utf-8 encoding and no conversion for newline characters

With no encoding, source code written in utf-8 (where non-ASCII characters (such as `Uɴɪᴏɴ`, `Fɪɴᴅ`, and other) non-ASCII characters in comments) may fail to be read by shift_jis (windows_31j, cp932). (There is also a way to specify the `-X utf8` option to python3)

- Added option to output directly to file instead of standard output.

When running on PowerShell, the encoding and newline characters of the `stdout` strings are sometimes converted, which makes it troublesome to take measures when redirecting output to a file, so I added an option to allow direct file output (if you are running on the (I guess it's no problem if you run it on command prompt, not on PowerShell (version 6 or later)...) Even with PowerShell (version 6 or later), you can use pipe instead of redirect `| Out-File -Encoding utf8 filepath.rs` (reconverted to UTF-8 without BOM) or something like that. (I could do that, but PowerShell5 seems to have only the option `-Encoding UTF-8` (UTF-8 with BOM), and what to do with newline characters, etc...)

**Comment by qryxip** [comment]
#109

**Comment by mizar** [comment]
Rebase commit to current `rust-lang-ja:master`.

**Review by qryxip — APPROVED** [review]
:+1:
Merging.

**Pull request merged**
