### PR TITLE
Update rust-toolchain to 1.70.0

### PR DESCRIPTION
**Pull request by togatoga**
Rust version of AtCoder is 1.70.0.

### CODE REVIEW

**Review by qryxip — CHANGES_REQUESTED** [review]
Could you update the `verify` job, too?
<https://github.com/rust-lang-ja/ac-library-rs/actions/runs/6284180412/job/17066036094?pr=137>

I think `1.71.1` is appropriate now.

<https://github.com/yosupo06/library-checker-judge/blob/6dc13ab410e9af91d57c110120cc1a9b2d6fe6b4/langs/Dockerfile.RUST#L5>

**Comment by qryxip** [comment]
I just remembered  #118. Other platforms such as yukicoder still use <1.70.0.

**Comment by TonalidadeHidrica** [comment]
We must continue discussing what is the appropriate MSRV on #118 , and this issue might as well be closed for now.

**Comment by togatoga** [comment]
@qryxip 

Sorry for my slow response.

> I just remembered #118. Other platforms such as yukicoder still use <1.70.0.

I think that we just need to focus on AtCoder platform. It's a tough to support all platforms.

**Review by koba-e964 — APPROVED** [review]

**Comment by togatoga** [comment]
@qryxip 
Could you approve this PR if it's ok to you? what else code should I fix?

**Comment by koba-e964** [comment]
I'm going to ignore tests that are not run and merge this PR, and then stop requiring 1.42.0-* tests to pass because they are stale.

**Pull request merged**
