### PR TITLE
Add internal modules into lib.rs and fix visibility

### PR DESCRIPTION
**Pull request by kenkoooo**
Add `internal_***` modules into `lib.rs` and fix the visibility of modules like the following:
- ~Change public modules from `mod` to `pub mod` so that the users can import them.~
- Make internal modules `pub(crate) mod` to allow other modules can use them internally.

### CODE REVIEW

**Comment by koba-e964** [comment]
I prefer exposing functions/structs directly in like `ac_library_rs::FenwickTree` by re-exporting in lib.rs
https://github.com/rust-lang-ja/ac-library-rs/blob/5809126cdbb8dcd3a632e5f114aa81202ef9d44c/src/lib.rs#L14
rather than `ac_library_rs::fenwick_tree::FenwickTree`.
That's because ACL adopts the same policy. (`using namespace atcoder;` imports everything.)

I'd like to hear what other contributors think.

**Comment by qryxip** [comment]
As a compromise, we have an another option to add `src/prelude.rs`.

That adapts to the policy of original ACL, I think. (as it is intended to use with `using namespace atcoder;`)

```rust
pub use crate::fenwicktree::FenwickTree; 
```

**Comment by qryxip** [comment]
We also have to take into consideration that this crate will be unlikely introduced to the system of AtCoder.

<https://twitter.com/chokudai/status/1303025509488496645>

The users have to expand the code with some tool. (e.g. [hatoo/cargo-snippet](https://github.com/hatoo/cargo-snippet))

**Comment by kenkoooo** [comment]
Thanks. That makes sense to me. Let me make `pub mod`s private.

**Comment by koba-e964** [comment]
Formatting is already done in branch `master`. Could you rebase this branch on top of `master`, instead of creating another commit to format the code?

**Review by koba-e964 — APPROVED** [review]

**Review by qryxip — APPROVED** [review]

**Comment by qryxip** [comment]
let us merge.

**Pull request merged**
