### PR TITLE
Implement `convolution`

### LINKED ISSUE #38: Implement convolution
Add a port of the ACL's convolution.hpp.

Please comment if you try.

### PR DESCRIPTION
**Pull request by qryxip**
Resolves #38.

### CODE REVIEW

**Comment by qryxip** [comment]
Finished?

BTW, why not add examples for Library-Cheker? As I said in the Slack before, verification for Library-Checker problems can be done automatically on the CI easily.

https://judge.yosupo.jp/submission/22484

**Comment by qryxip** [comment]
https://github.com/atcoder/ac-library/issues/30

**Comment by qryxip** [comment]
oh no I didn't implement `convolution<mod, T>`

**Review by matsu7874 — APPROVED** [review]
LGTM

**Pull request merged**
